"""Add product detail fields

Revision ID: 0204433abb2f
Revises: f46d7050d99b
Create Date: 2026-06-30 15:19:11.688531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0204433abb2f'
down_revision: Union[str, Sequence[str], None] = 'f46d7050d99b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('price', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('mrp', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('discount_percentage', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('rating', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('review_count', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('availability', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('product_url', sa.String(length=500), nullable=True))
    op.create_unique_constraint(None, 'products', ['product_url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='unique')
    op.drop_column('products', 'product_url')
    op.drop_column('products', 'description')
    op.drop_column('products', 'availability')
    op.drop_column('products', 'review_count')
    op.drop_column('products', 'rating')
    op.drop_column('products', 'discount_percentage')
    op.drop_column('products', 'mrp')
    op.drop_column('products', 'price')
    # ### end Alembic commands ###
