"""Add soft delete to products

Revision ID: a05a16d5f7e9
Revises: e3acc5db9634
Create Date: 2026-06-25 21:00:45.042624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a05a16d5f7e9'
down_revision: Union[str, Sequence[str], None] = 'e3acc5db9634'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.false(),))
    op.add_column('products', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'deleted_at')
    op.drop_column('products', 'is_deleted')
    # ### end Alembic commands ###
